k8s_ver: 1.8.1
# k8s_next_ver: 1.x.y
etcd_ver: 3.2.9
# etcd_next_ver: 3.u.v
apiserver_count: 3
dns_service_ip: 172.16.0.10
service_ip_range: 172.16.0.0/16
apiserver_service_ip: 172.16.0.1
pod_ip_range: 10.11.0.0/16
apiserver_cpu: 150m
apiserver_memory: 400Mi
etcd_cpu: 150m
etcd_memory: 250Mi
kube_proxy_cpu: 100m
kube_scheduler_cpu: 150m
kube_cm_cpu: 200m
eviction_memory: 50Mi
eviction_nodefs: 300Mi
eviction_imagefs: 300Mi
system_reserved_cpu: 100m
system_reserved_memory: 150Mi
graphite_server: 158.38.213.209
zabbix_server: zabbix-backend.uninett.no
oidc_issuer_url: https://test.dataporten-api.no
oidc_client_id: xxxxx-xxxxx-xxxx-xxxxx-xxxx
oidc_groups_claim: principals
lvm_vg_name: vg
calico_ipip: "always"
calico_node_ver: 2.6.1
calico_cni_ver: 1.11.0
calico_k8s_policy_ver: 1.0.0
fed_public_api_ip: 158.36.100.28
fed_api_token: a08df6b23deef35a48999aa8d209eba4
fed_zone_name: researchlab.no.
fed_name: researchlab
ss_api_server: 2.3.4.5
uh_iaas_api_server: 1.2.3.4
