apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab
  namespace: kube-system

---

# This ClusterRole is inspired by the default `edit` role in Kubernetes, with some changes.
# * We don't grant access to reading secrets, nor impersonating service accounts.
# * We add access to creating ingress & networkpolicy.
# * We add access to creating & updating secrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitlab
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - endpoints
      - persistentvolumeclaims
      - pods
      - pods/attach
      - pods/exec
      - pods/portforward
      - pods/proxy
      - replicationcontrollers
      - replicationcontrollers/scale
      - secrets
      - serviceaccounts
      - services
      - services/proxy
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
      - deletecollection
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - update
  - apiGroups:
      - ""
    resources:
      - bindings
      - events
      - limitranges
      - namespaces
      - namespaces/status
      - pods/log
      - pods/status
      - replicationcontrollers/status
      - resourcequotas
      - resourcequotas/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
      - deletecollection
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
      - deletecollection
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
      - scheduledjobs
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
      - deletecollection
  - apiGroups:
      - extensions
    resources:
      - daemonsets
      - deployments
      - deployments/scale
      - horizontalpodautoscalers
      - ingresses
      - jobs
      - networkpolicies
      - replicasets
      - replicasets/scale
      - replicationcontrollers/scale
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
      - deletecollection
  - apiGroups:
      - extensions
    resources:
      - ingresses/status
    verbs:
      - get
      - list
      - watch

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab
  namespace: default
subjects:
  - kind: ServiceAccount
    name: gitlab
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: gitlab
  apiGroup: rbac.authorization.k8s.io
